baseURL: 'https://rmi.lbi.ro/'
title: Romanian Master of Sciences Example Config

languageCode: en-us
enableRobotsTXT: true
canonifyURLs: true
theme: rms-theme
staticDir:
  - static/
  - favicon/

params:
  logo: /assets/logo.svg
  heading: 'October 1rd - October 2th, 2048'
  author: Ciprian Ionescu
  author_url: 'https://ciprian-ionescu.com/'
  useSlider: false
  baseColor: '#a50'
  finished: false

menu:
  main:
    - identifier: root
      name: RMS 2048
      title: RMS 2048
      weight: 1

    - identifier: organisation
      name: RMS Organisation
      title: RMS Organisation
      weight: 2

    - identifier: contest
      name: RMS Contest
      title: RMS Contest
      weight: 3

    - identifier: info
      name: General Information
      title: General Information
      weight: 4

    - url: 'https://en.wikipedia.org/wiki/Romania'
      name: About Romania
      title: About Romania
      parent: info
      weight: 1

    - url: 'https://en.wikipedia.org/wiki/Bucharest'
      name: About Bucharest
      title: About Bucharest
      parent: info
      weight: 2

    - url: 'http://www.romaniatourism.com/'
      name: Tourist Guide
      title: Tourist Guide
      parent: info
      weight: 3

markup:
  goldmark:
    renderer:
      unsafe: true
